server:
    port: 8080

spring:
    application:
        name: spring-cloud-project-producer-client
    datasource:
        url: jdbc:mysql://47.240.95.83:3360/zhxy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: myself
        password: wang@123
        driver-class-name: com.mysql.cj.jdbc.Driver
#    rabbitmq:
#        host: 47.240.95.83
#        port: 5672
#        username: guest
#        password: guest
#        listener:
#            simple:
#                acknowledge-mode: manual #手动ack
    cloud:
        circuitbreaker:
            hystrix:
                enabled: true


eureka:
    instance:
        appname: ${spring.application.name}
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka/
mybatis:
    mapper-locations: classpath:static/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.wjf.github.commons.domain.producer

logging:
    level:
        com.wjf.github.producerclient.mapper: debug