server:
    port: 8080

spring:
    application:
        name: spring-cloud-project-producer-client
    datasource:
        url: jdbc:mysql://47.240.95.83:3360/zhxy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: myself
        password: wang@123
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            #初始化时建立物理连接的个数
            initial-size: 5
            #最小连接池数量
            min-idle: 5
            #最大连接池数量 maxIdle已经不再使用
            max-active: 20
            #获取连接时最大等待时间，单位毫秒
            max-wait: 60000
            #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            test-while-idle: true
            #既作为检测的间隔时间又作为testWhileIdel执行的依据
            time-between-eviction-runs-millis: 60000
            #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
            min-evictable-idle-time-millis: 300000
            #用来检测连接是否有效的sql 必须是一个查询语句
            #mysql中为 select 'x'
            #oracle中为 select 1 from dual
            validation-query: select 'x'
            #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-borrow: false
            #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
            test-on-return: false
            #当数据库抛出不可恢复的异常时,抛弃该连接
            exception-sorter: true
            #是否缓存preparedStatement,mysql5.5+建议开启
            pool-prepared-statements: true
            #当值大于0时poolPreparedStatements会自动修改为true
            max-pool-prepared-statement-per-connection-size: 20
            #配置扩展插件
            filters: stat,wall
#            connection-properties:
#                druid:
#                    stat:
#                        mergeSql: true
            filter:
                stat:
#                    打开mergeSql功能；慢SQL记录
                    slow-sql-millis: 500
                    merge-sql: true
            #合并多个DruidDataSource的监控数据
            use-global-data-source-stat: true
            stat-view-servlet:
                #设置访问druid监控页的账号,默认没有
                login-username: admin
                #设置访问druid监控页的密码,默认没有
                login-password: admin
#    rabbitmq:
#        host: 47.240.95.83
#        port: 5672
#        username: guest
#        password: guest
#        listener:
#            simple:
#                acknowledge-mode: manual #手动ack
    cloud:
        circuitbreaker:
            hystrix:
                enabled: true


eureka:
    instance:
        appname: ${spring.application.name}
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://127.0.0.1:7001/eureka/
mybatis:
    mapper-locations: classpath:static/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.wjf.github.commons.domain.producer

logging:
    level:
        com.wjf.github.producerclient.mapper: debug