server:
    port: 8081
    servlet:
        context-path: /userinfoConsumerClient
spring:
    application:
        name: spring-cloud-project-userinfo-consumer-client
#    rabbitmq:
#        host: 47.240.95.83
#        port: 5672
#        username: guest
#        password: guest
#        publisher-returns: true #发送返回
#        publisher-confirm-type: correlated #发送手动ack
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
           defaultZone: http://127.0.0.1:7001/eureka/
    instance:
        appname: ${spring.application.name}

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000

ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000

feign:
#    httpclient:
#        enabled: true
#        connection-timeout: 3000
#        connection-timer-repeat: 6000
    hystrix:
        enabled: true